language: python
python:
 - "2.6"
 - "2.7"
 - "pypy"
env:
 - FLASK_VERSION=0.8
 - FLASK_VERSION=0.9
install:
 - "pip install -r testapp/requirements.txt --use-mirrors"
 - "pip install -I Flask==$FLASK_VERSION"
 - "pip install -e ."
script: "unit2 discover -s testapp/"
